// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

// API
export const API_FETCH = 'API_FETCH';
export const API_FAILED = 'API_FAILED';
export const API_DEFAULT = 'API_DEFAULT';

// Auth
export const AUTH_GET_TOKEN = 'AUTH_GET_TOKEN';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_DISCARD_TOKEN = 'AUTH_DISCARD_TOKEN';
export const GET_INFO_USER = 'GET_INFO_USER';
export const SWITCH_ROLE = 'SWITCH_ROLE';

// User
export const USER_FETCH = 'USER_FETCH';
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';

// Role
export const ROLE_FETCH = 'ROLE_FETCH';
export const ROLE_FETCH_SUCCESS = 'ROLE_FETCH_SUCCESS';

// User-Role
export const USER_ROLE_FETCH = 'USER_ROLE_FETCH';
export const USER_ROLE_FETCH_SUCCESS = 'USER_ROLE_FETCH_SUCCESS';
export const ROLE_BY_USER_FETCH = 'ROLE_BY_USER_FETCH';
export const ROLE_BY_USER_FETCH_SUCCESS = 'ROLE_BY_USER_FETCH_SUCCESS';
export const USER_BY_ROLE_FETCH = 'USER_BY_ROLE_FETCH';
export const USER_BY_ROLE_FETCH_SUCCESS = 'USER_BY_ROLE_FETCH_SUCCESS';

//Contact Module const
export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';